# Build stage
FROM node:20-alpine AS builder
RUN apk update
RUN apk add --no-cache libc6-compat
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN pnpm install

# Copy source files
COPY . .

# Run dev in a detach mode
RUN pnpm run dev &

# Build the project in static mode
RUN pnpm run build

# Expose port 4321
EXPOSE 4322

# Load environment variables
COPY .env .env
RUN chmod +x /app/start.sh
# Start API
RUN /app/start.sh &
